name: Deploy Svelte to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "135739796+dionisiyKDO@users.noreply.github.com"
          git config --global user.name "Denys Kamiskyi"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          npm install -g gh-pages
          gh-pages -d build --repo "https://${{ secrets.GH_PAT }}@github.com/dionisiyKDO/dionisiyKDO.github.io.git"
