name: Deploy Svelte to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "dionisiy.kdo@gmail.com"
          git config --global user.name "Denys"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d build --repo "https://${{ secrets.GITHUB_TOKEN }}@github.com/dionisiyKDO/dionisiyKDO.github.io.git"
